import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface LegalPageProps {
  onBack: () => void;
}

export const LegalTerms: React.FC<LegalPageProps> = ({ onBack }) => {
  return (
    <div className="max-w-3xl mx-auto pb-16">
      <button
        onClick={onBack}
        className="flex items-center gap-1.5 text-xs font-mono font-bold uppercase text-[#2D4A3E] hover:underline mb-6"
      >
        <ArrowLeft className="w-4 h-4" />
        <span>Back to App</span>
      </button>

      <article className="bg-[#F7F2EB] border border-[#E5E0D8] rounded-2xl p-6 md:p-10 shadow-sm">
        <h1 className="text-3xl font-serif italic text-[#1F1F1F] mb-2">Terms of Service</h1>
        <p className="text-xs font-mono text-[#1F1F1F]/50 mb-8">Last updated: June 2026</p>

        <div className="space-y-6 text-sm text-[#1F1F1F]/80 leading-relaxed">
          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-[#2D4A3E] mb-2">
              Educational Project
            </h2>
            <p>
              Wobble is an educational AI guardian and rescue system.
              It is provided as-is for learning purposes and productivity experimentation. It is not a
              commercial product and does not constitute professional advice of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-[#2D4A3E] mb-2">
              AI Output May Be Inaccurate
            </h2>
            <p>
              Task plans, rescue strategies, risk scores, deadlines, and subtasks are generated by Google&apos;s
              Gemini AI. AI-generated content may be incomplete, incorrect, or inappropriate for your specific
              situation. Always review AI suggestions critically before relying on them for important decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-[#2D4A3E] mb-2">
              User Responsibility
            </h2>
            <p>
              You are solely responsible for decisions you make based on information provided by this
              application. The developers assume no liability for missed deadlines, academic outcomes, work
              performance, or any other consequences resulting from use of this tool. Use your own judgment
              and verify critical information independently.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-mono font-bold uppercase tracking-widest text-[#2D4A3E] mb-2">
              Usage Limits
            </h2>
            <p>
              To manage service costs, AI generation requests are limited per month. These limits may change
              without notice. Continued use of the application constitutes acceptance of these terms.
            </p>
          </section>
        </div>
      </article>
    </div>
  );
};
